name: lab1_water
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3 
  connectivity_plus: ^6.0.3 
  mqtt_client: ^10.11.10
  dio: ^5.4.0
  flutter_bloc: ^9.1.1
  my_flashlight_plugin:
    git:
      url: https://github.com/olyaoes/my_flashlight_plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  web: 0.1.4-beta

flutter:
  uses-material-design: true